#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hypre
Version  : 2.18.2
Release  : 4
URL      : https://github.com/hypre-space/hypre/archive/v2.18.2.tar.gz
Source0  : https://github.com/hypre-space/hypre/archive/v2.18.2.tar.gz
Summary  : Library of high performance preconditioners and solvers
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: hypre-lib = %{version}-%{release}
Requires: hypre-license = %{version}-%{release}
Requires: hypre-openmpi = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : modules
BuildRequires : openblas-dev
BuildRequires : openmpi-dev
BuildRequires : openssh

%description
HYPRE is a library of high performance preconditioners and solvers
featuring multigrid methods for the solution of large, sparse linear
systems of equations on massively parallel computers.

%package dev
Summary: dev components for the hypre package.
Group: Development
Requires: hypre-lib = %{version}-%{release}
Requires: hypre-openmpi = %{version}-%{release}
Provides: hypre-devel = %{version}-%{release}
Requires: hypre = %{version}-%{release}

%description dev
dev components for the hypre package.


%package lib
Summary: lib components for the hypre package.
Group: Libraries
Requires: hypre-license = %{version}-%{release}

%description lib
lib components for the hypre package.


%package license
Summary: license components for the hypre package.
Group: Default

%description license
license components for the hypre package.


%package openmpi
Summary: openmpi components for the hypre package.
Group: Default

%description openmpi
openmpi components for the hypre package.


%prep
%setup -q -n hypre-2.18.2
cd %{_builddir}/hypre-2.18.2
pushd ..
cp -a hypre-2.18.2 buildavx2
popd
pushd ..
cp -a hypre-2.18.2 build-openmpi
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586648967
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
pushd src
%configure --disable-static --prefix=%{buildroot}/usr --libdir=%{buildroot}/usr/lib64 --includedir=%{buildroot}/usr/include \
--enable-shared --enable-fortran \
--without-MPI --with-openmp \
--with-blas-libs=blas --with-blas-lib-dirs=/usr/lib64 \
--with-lapack-libs=lapack --with-lapack-lib-dirs=/usr/lib64 \
LDFLAGS="$LDFLAGS -fopenmp" CFLAGS="$CFLAGS -fopenmp" FFLAGS="$FFLAGS -fopenmp"
make  %{?_smp_mflags}
popd

unset PKG_CONFIG_PATH
pushd ../buildavx2/src
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export FFLAGS="$FFLAGS -m64 -march=haswell"
export FCFLAGS="$FCFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%configure --disable-static --prefix=%{buildroot}/usr --libdir=%{buildroot}/usr/lib64 --includedir=%{buildroot}/usr/include \
--enable-shared --enable-fortran \
--without-MPI --with-openmp \
--with-blas-libs=blas --with-blas-lib-dirs=/usr/lib64 \
--with-lapack-libs=lapack --with-lapack-lib-dirs=/usr/lib64 \
LDFLAGS="$LDFLAGS -fopenmp" CFLAGS="$CFLAGS -fopenmp" FFLAGS="$FFLAGS -fopenmp"
make  %{?_smp_mflags}
popd
pushd ../build-openmpi/src
. /usr/share/defaults/etc/profile.d/modules.sh
module load openmpi
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export FCFLAGS="$FCFLAGS -m64 -march=haswell"
export FFLAGS="$FFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
./configure --program-prefix=  --exec-prefix=$MPI_ROOT \
--libdir=$MPI_LIB --bindir=$MPI_BIN --sbindir=$MPI_BIN --includedir=$MPI_INCLUDE \
--datarootdir=$MPI_ROOT/share --mandir=$MPI_MAN -exec-prefix=$MPI_ROOT --sysconfdir=$MPI_SYSCONFIG \
--build=x86_64-generic-linux-gnu --host=x86_64-generic-linux-gnu --target=x86_64-clr-linux-gnu  \
--disable-static --prefix=%{buildroot}/$MPI_ROOT --libdir=%{buildroot}/$MPI_LIB --includedir=%{buildroot}/$MPI_INCLUDE \
--enable-shared --enable-fortran \
--with-MPI --without-openmp \
--with-blas-libs=blas --with-blas-lib-dirs=/usr/lib64 \
--with-lapack-libs=lapack --with-lapack-lib-dirs=/usr/lib64
make  %{?_smp_mflags}
module unload openmpi
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd ../build-openmpi/src
module load openmpi
export OMPI_MCA_rmaps_base_oversubscribe=1
make check
module unload openmpi
popd
pushd ../buildavx2/src
make check
popd
pushd src
make check
popd

%install
export SOURCE_DATE_EPOCH=1586648967
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hypre
cp %{_builddir}/hypre-2.18.2/COPYRIGHT %{buildroot}/usr/share/package-licenses/hypre/37aa7479e190bdd98c6d0ac64a5b4eeb3fc275e3
cp %{_builddir}/hypre-2.18.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/hypre/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/hypre-2.18.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/hypre/abcfa67b269101912345a96936a16766b8d5d597
cp %{_builddir}/hypre-2.18.2/src/blas/COPYING %{buildroot}/usr/share/package-licenses/hypre/1f5f28746f9bdb5c6ce2a498119fc3258b977f71
cp %{_builddir}/hypre-2.18.2/src/docs/copyright.txt %{buildroot}/usr/share/package-licenses/hypre/e20825a5cf4179d1c5329114ea0fd9f6a2f910ad
cp %{_builddir}/hypre-2.18.2/src/lapack/COPYING %{buildroot}/usr/share/package-licenses/hypre/1f5f28746f9bdb5c6ce2a498119fc3258b977f71
pushd ../buildavx2/src
%make_install_avx2
popd
pushd ../build-openmpi/src
module load openmpi
%make_install_openmpi
module unload openmpi
popd
pushd src
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/HYPRE.h
/usr/include/HYPRE_DistributedMatrixPilutSolver_protos.h
/usr/include/HYPRE_DistributedMatrixPilutSolver_types.h
/usr/include/HYPRE_IJ_mv.h
/usr/include/HYPRE_MatvecFunctions.h
/usr/include/HYPRE_config.h
/usr/include/HYPRE_error_f.h
/usr/include/HYPRE_krylov.h
/usr/include/HYPRE_lobpcg.h
/usr/include/HYPRE_matrix_matrix_protos.h
/usr/include/HYPRE_parcsr_ls.h
/usr/include/HYPRE_parcsr_mv.h
/usr/include/HYPRE_seq_mv.h
/usr/include/HYPRE_sstruct_ls.h
/usr/include/HYPRE_sstruct_mv.h
/usr/include/HYPRE_struct_ls.h
/usr/include/HYPRE_struct_mv.h
/usr/include/HYPRE_utilities.h
/usr/include/HYPREf.h
/usr/include/_hypre_IJ_mv.h
/usr/include/_hypre_parcsr_ls.h
/usr/include/_hypre_parcsr_mv.h
/usr/include/_hypre_sstruct_ls.h
/usr/include/_hypre_sstruct_mv.h
/usr/include/_hypre_struct_ls.h
/usr/include/_hypre_struct_mv.h
/usr/include/_hypre_utilities.h
/usr/include/csr_block_matrix.h
/usr/include/csr_matmultivec.h
/usr/include/distributed_matrix.h
/usr/include/fortran.h
/usr/include/fortran_matrix.h
/usr/include/hypre_hopscotch_hash.h
/usr/include/interpreter.h
/usr/include/krylov.h
/usr/include/lobpcg.h
/usr/include/multivector.h
/usr/include/par_csr_block_matrix.h
/usr/include/par_csr_matmultivec.h
/usr/include/par_csr_pmvcomm.h
/usr/include/par_multivector.h
/usr/include/seq_multivector.h
/usr/include/seq_mv.h
/usr/include/temp_multivector.h
/usr/lib64/openmpi/include/HYPRE.h
/usr/lib64/openmpi/include/HYPRE_DistributedMatrixPilutSolver_protos.h
/usr/lib64/openmpi/include/HYPRE_DistributedMatrixPilutSolver_types.h
/usr/lib64/openmpi/include/HYPRE_IJ_mv.h
/usr/lib64/openmpi/include/HYPRE_MatvecFunctions.h
/usr/lib64/openmpi/include/HYPRE_config.h
/usr/lib64/openmpi/include/HYPRE_error_f.h
/usr/lib64/openmpi/include/HYPRE_krylov.h
/usr/lib64/openmpi/include/HYPRE_lobpcg.h
/usr/lib64/openmpi/include/HYPRE_matrix_matrix_protos.h
/usr/lib64/openmpi/include/HYPRE_parcsr_ls.h
/usr/lib64/openmpi/include/HYPRE_parcsr_mv.h
/usr/lib64/openmpi/include/HYPRE_seq_mv.h
/usr/lib64/openmpi/include/HYPRE_sstruct_ls.h
/usr/lib64/openmpi/include/HYPRE_sstruct_mv.h
/usr/lib64/openmpi/include/HYPRE_struct_ls.h
/usr/lib64/openmpi/include/HYPRE_struct_mv.h
/usr/lib64/openmpi/include/HYPRE_utilities.h
/usr/lib64/openmpi/include/HYPREf.h
/usr/lib64/openmpi/include/_hypre_IJ_mv.h
/usr/lib64/openmpi/include/_hypre_parcsr_ls.h
/usr/lib64/openmpi/include/_hypre_parcsr_mv.h
/usr/lib64/openmpi/include/_hypre_sstruct_ls.h
/usr/lib64/openmpi/include/_hypre_sstruct_mv.h
/usr/lib64/openmpi/include/_hypre_struct_ls.h
/usr/lib64/openmpi/include/_hypre_struct_mv.h
/usr/lib64/openmpi/include/_hypre_utilities.h
/usr/lib64/openmpi/include/csr_block_matrix.h
/usr/lib64/openmpi/include/csr_matmultivec.h
/usr/lib64/openmpi/include/distributed_matrix.h
/usr/lib64/openmpi/include/fortran.h
/usr/lib64/openmpi/include/fortran_matrix.h
/usr/lib64/openmpi/include/hypre_hopscotch_hash.h
/usr/lib64/openmpi/include/interpreter.h
/usr/lib64/openmpi/include/krylov.h
/usr/lib64/openmpi/include/lobpcg.h
/usr/lib64/openmpi/include/multivector.h
/usr/lib64/openmpi/include/par_csr_block_matrix.h
/usr/lib64/openmpi/include/par_csr_matmultivec.h
/usr/lib64/openmpi/include/par_csr_pmvcomm.h
/usr/lib64/openmpi/include/par_multivector.h
/usr/lib64/openmpi/include/seq_multivector.h
/usr/lib64/openmpi/include/seq_mv.h
/usr/lib64/openmpi/include/temp_multivector.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libHYPRE-2.18.2.so
/usr/lib64/haswell/libHYPRE.so
/usr/lib64/libHYPRE-2.18.2.so
/usr/lib64/libHYPRE.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hypre/1f5f28746f9bdb5c6ce2a498119fc3258b977f71
/usr/share/package-licenses/hypre/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/hypre/37aa7479e190bdd98c6d0ac64a5b4eeb3fc275e3
/usr/share/package-licenses/hypre/abcfa67b269101912345a96936a16766b8d5d597
/usr/share/package-licenses/hypre/e20825a5cf4179d1c5329114ea0fd9f6a2f910ad

%files openmpi
%defattr(-,root,root,-)
/usr/lib64/openmpi/lib/libHYPRE-2.18.2.so
/usr/lib64/openmpi/lib/libHYPRE.so
